version: '3'
services:
  localstack:
    image: localstack/localstack:3.8
    ports:
      - 4566:4566
    environment:
      - SERVICES=dynamodb,kinesis,s3,sqs,sns,ssm
      - AWS_CBOR_DISABLE=1
      - DEFAULT_REGION=us-east-1
    volumes:
      - ./init:/etc/localstack/init/ready.d/
